services:
  ocai:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_URL: ${DB_URL}
      TRANSCRIPT_API_TOKEN: ${TRANSCRIPT_API_TOKEN}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POCKETBASE_URL: ${POCKETBASE_URL}
      POCKETBASE_EMAIL: ${POCKETBASE_EMAIL}
      POCKETBASE_PASSWORD: ${POCKETBASE_PASSWORD}
      MODEL: ${MODEL}
