[project]
name = "clem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.4.0",
    "promptic>=0.7.7",
    "loguru>=0.7.2",
    "google-generativeai>=0.7.2",
    "tenacity>=9.0.0",
    "youtube-transcript-api>=0.6.2",
    "flask>=3.0.3",
    "pocketbase>=0.12.3",
    "audioop-lts>=0.2.1",
    "free-proxy>=1.1.3",
]

[project.scripts]
clem = "clem.discord:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 79
