[project]
name = "clem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.4.0",
    "promptic>=0.7.7",
    "loguru>=0.7.2",
    "supabase>=2.7.3",
    "dataset>=1.6.2",
    "psycopg2-binary>=2.9.9",
    "google-generativeai>=0.7.2",
    "tenacity>=9.0.0",
]

[project.scripts]
clem = "clem:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 79
